### PR TITLE
ci: drop support for Python 3.6

### PR DESCRIPTION
**Pull request by owenvoke**
I've also bumped `actions/checkout` and `actions/setup-python` to the latest versions. 👍🏻

I don't know enough about Python to know why the tests are failing, however. 👀

### CODE REVIEW

**Comment by kbdharun** [comment]
Seems like the build fails now too.

**Comment by owenvoke** [comment]
Looks like it's failing because the tests are expecting single quotes in output, whereas they are being given double quotes? 👀

**Comment by kbdharun** [comment]
> Looks like it's failing because the tests are expecting single quotes in output, whereas they are being given double quotes? 👀

Oh 👀

**Comment by owenvoke** [comment]
Actually, that might be irrelevant. 🤷🏻 I will see if I can bump pytest when I get home and see if that helps.

**Comment by kbdharun** [comment]
Nice, The CI passed 🥳

**Comment by owenvoke** [comment]
Looks like my changes have been applied separately, so closing this PR 👍🏻

**Pull request closed without merging**
