### PR TITLE
Change language priority for environment variables

### PR DESCRIPTION
**Pull request by columbarius**
Regarding the language priority discussed in #122 and  tldr-pages/tldr#4101 I have implemented a solution. My suggestion would be a priority like that
| TLDR_LANGUAGE | LANG | LANGUAGES | Result |
| --- | --- | --- | --- |
| fr | de | it,fr,de | fr |
| ! | de | it,fr,de | de,it,fr,en |
| ! | ! | it,fr,de | it,fr,de,en |
| ! | de | ! | de,en |

, while ! is unset.

I'm also interested, where LANGUAGES originates from. While I couldn't find a notion of it in the archwiki, or at [gnu.org](https://www.gnu.org/software/gettext/manual/html_node/Locale-Environment-Variables.html#Locale-Environment-Variables), I found the LANGUAGE environment variable instead.

Since this topic is still in discussion I'm submitting this as a draft in case it could be useful.

### CODE REVIEW

**Comment by zdroid** [comment]
Does it agree with the specification, though? I think it should be `fr, en` in the first row. Either way, I think it'd be useful if you posted your ideas in https://github.com/tldr-pages/tldr/pull/4101.

**Comment by MasterOdin** [comment]
> I'm also interested, where LANGUAGES originates from. While I couldn't find a notion of it in the archwiki, or at gnu.org, I found the LANGUAGE environment variable instead.

Because I'm bad at typing and it should be `LANGUAGE`. Opening a PR now for that.

**Comment by columbarius** [comment]
> Does it agree with the specification, though? I think it should be `fr, en` in the first row. 

I read TLDR_LANGUAGE in the same role of the --language flag to replace all other languages.
> Either way, I think it'd be useful if you posted your ideas in tldr-pages/tldr#4101.

All right, then I will do that.

> Because I'm bad at typing and it should be `LANGUAGE`. Opening a PR now for that.
Ok, thanks.

**Comment by columbarius** [comment]
I've updated the language handling to fit my proposal in https://github.com/tldr-pages/tldr/issues/4092#issuecomment-647036499 to test it for convenience.

**Comment by columbarius** [comment]
Since https://github.com/tldr-pages/tldr/pull/4101 was merged I changed this from Draft to PR.

**Comment by columbarius** [comment]
Should I bump __client_specification__ to 1.3 in this PR, or would this be done in an extra commit?

**Comment by zdroid** [comment]
@columbarius go ahead, nice catch!

**Comment by columbarius** [comment]
client_specification bumped. I guess, I should have written this earlier to trigger a notification?

**Comment by zdroid** [comment]
No need, I am just leaving the final merge decision to @MasterOdin.

**Comment by MasterOdin** [comment]
Thanks for this. Still some refactoring I'd like to do in the next week or so before cutting a new release.

**Comment by columbarius** [comment]
Ok, thanks for merging.

**Pull request merged**
