### PR TITLE
Update page source to use main branch

### PR DESCRIPTION
**Pull request by kbdharun**
I noticed `TLDR_PAGES_SOURCE_LOCATION` and other links pointed to the `master` branch which is no longer our primary branch so It is better to update it to `main`.

### CODE REVIEW

**Review by owenvoke — APPROVED** [review]

**Comment by kbdharun** [comment]
I have no idea, why the build fails. @owenvoke What might be the cause?

**Comment by owenvoke** [comment]
Looks like Python 3.6 is no longer supported by `setup-python`, we can probably drop this as part of another PR as it's EOL. 👍🏻

**Review by navarroaxel — APPROVED** [review]

**Comment by MasterOdin** [comment]
@kbdharun Could you please rebase onto the latest `main`?

**Comment by kbdharun** [comment]
> @kbdharun Could you please rebase onto the latest `main`?

Done 👍🏽

**Comment by kbdharun** [comment]
After this PRs merge should we create a release?

**Pull request merged**
