### PR TITLE
img

### PR DESCRIPTION
**Pull request by VictoriaLa**

### CODE REVIEW

**Comment by JacobCallahan** [comment]
@VictoriaLa can you elaborate on this issue?

**Comment by JacobCallahan** [comment]
The opening bracket renders in the preview.
Screenshot from 2019-10-21 09-28-41

**Comment by waldyrious** [comment]
I'm not sure it's worth adding a generic logo to a specific client like this. If it were branded (e.g. to incorporate some reference to Python), then it might make sense; but as it is, IMO it risks confusing the client with the overall project, which is not the intent (this is just one of several clients for the tldr pages).

I'd suggest either reworking the image into a logo proposal specific to this client, or otherwise closing this issue and participating in the ongoing discussion at https://github.com/tldr-pages/tldr/issues/2986.

**Comment by zdroid** [comment]
I'm against this. We have the logo in the main repository, and it'd be really be needless to put it everywhere. Do others agree with closing the issue?

ping @waldyrious

**Comment by waldyrious** [comment]
As I mentioned above, I'm not opposed to having a specific logo/image for this client, but neither the image proposed in this PR nor the project-wide logo we implemented in tldr-pages/tldr#2986 would be suitable for that purpose.

Since we had no feedback from the opener of the PR after almost 3 months, I agree we can close the PR, with the understanding that it can be reopened if the author (or someone else) wishes to rework it based on the feedback above.

**Pull request closed without merging**
