### PR TITLE
update pyp versions for tests

### PR DESCRIPTION
**Pull request by lots0logs**

### CODE REVIEW

**Comment by waldyrious** [comment]
@lots0logs pypy-5.5 [doesn't seem to be available on Travis](https://docs.travis-ci.com/user/languages/python/#PyPy-Support).

https://github.com/travis-ci/travis-ci/issues/4756 has related discussion -- particularly, [this comment](https://github.com/travis-ci/travis-ci/issues/4756#issuecomment-138102705) says:

> ubuntu 14.04 is at pypy 2.2

**Comment by lots0logs** [comment]
@waldyrious Alright, its (finally) good to go :+1:

**Comment by waldyrious** [comment]
Nice work! For future reference, how does one figure out the correct pypy version format to use? Is there a list publicly available somewhere?

**Comment by lots0logs** [comment]
@waldyrious Sadly, no there isn't. I found the version I used in this PR while looking through their github issues that had mention of "pypy" in them :roll_eyes:

**Comment by waldyrious** [comment]
That's too bad. Thanks for confirming.

**Pull request merged**
