### PR TITLE
Use default terminal colors instead of white by default

### LINKED ISSUE #95: Do not specify default color by default for white text
In the code, tldr defines default colors to use for all attributes:
https://github.com/tldr-pages/tldr-python-client/blob/c10b95aa5c6549361d6e986798d42245b79a08d9/tldr.py#L183-L190

As pointed out in #94, these look terrible on non-dark backgrounds as white does not show up well. This is due to the specifying of the `white` color by default for a number of elements. However, instead of specifying this `white` default, why not just leave it blank and use the user set text color within their editor? This is probably what the user wants anyway by default and is somewhat guaranteed to look fine for them.

The actual code change here would be to pass `None` back as the first argument of the tuple from `of_colors`.

### PR DESCRIPTION
**Pull request by MasterOdin**
Closes #95 

Closes #94 (sorta)

Removes the white default color from TLDR commands, as well as allows you to specify a blank string for one of the colors and it will work as expected by using the default color from the terminal.

This also fixes an issue where if you could only one word in the environment string and not a combination of things as the `user_value not in ACCEPTED_COLORS` check would always fail otherwise.

### CODE REVIEW

**Comment by KyleWJohnston** [comment]
Works great for me, but do we want to set `blank`, `name`, `description`, and `parameter` to an empty string so that no user configuration is required?

**Comment by zdroid** [comment]
@KyleWJohnston It's compatible with the way colors are done in Bash. If you specify none, it's set to default.

**Comment by KyleWJohnston** [comment]
Whoops, I was looking at the wrong branch. It works without configuration for me too.

**Comment by zdroid** [comment]
@MasterOdin @KyleWJohnston I think blank color can be dropped altogether, as it's supposed to be... blank. I'm working in #98 on simplifying the way that pages are displayed.

**Comment by MasterOdin** [comment]
I suspect the idea of the blank variable is that if you wanted to give a colored background for the entire output, you would want to set the background there. Like, in #20, if you just outputted an empty line, then the lines with no text would have a black background while the other lines would still have blue background here and there, and it would look like a mess.

**Comment by zdroid** [comment]
@MasterOdin Check the latest change. It should be highlighted perfectly now.

**Comment by MasterOdin** [comment]
@zdroid Given that this PR is necessary to get colors and attributes working as expected (and from environment variables), and have a meaningful discussion on `BLANK` (which you are removing / editing in #98), I would probably recommend merging this PR first, and then continuing the discussion on removing `BLANK` (or not) there.

**Comment by zdroid** [comment]
Fair point, I realized that too after making the changes.

**Pull request merged**
