### PR TITLE
feat: add BSD and macos platforms to `--platform` option

### PR DESCRIPTION
**Pull request by owenvoke**
Closes https://github.com/tldr-pages/tldr-python-client/issues/234 and closes https://github.com/tldr-pages/tldr-python-client/issues/235

### CODE REVIEW

**Comment by acuteenvy** [comment]
This doesn't work, because `macos` is not a directory. `tldr --platform macos <page_name>` always prints "documentation is not available".

There's also `android`, which isn't on the list here.

**Comment by owenvoke** [comment]
Ah, so we need to actually alias them. Will mark this as draft and work on the required changes.

**Comment by kbdharun** [comment]
Hi, any updates on this?

**Comment by kbdharun** [comment]
Completed in #246

**Pull request closed without merging**
