### PR TITLE
Fix options not working properly

### LINKED ISSUE #62: Cannot use most CLI options
Cannot use most of the options (like os or source), due to:
https://github.com/tldr-pages/tldr-python-client/blob/06ac37a7f0bbb207b179e16688229b89a2ee1435/tldr.py#L286-L295
line 295 overwrites the option array set on line 286 (which did contain os, source, etc.) and replaces it with the defaults for those options.

Test command:
```shell
./tldr -s sunos svcs
`svcs` documentation is not availableConsider contributing Pull Request to https://github.com/tldr-pages/tldr
```

The namespace before and after the pointed out line:
```
Before: Namespace(os=['sunos'], source='http://raw.github.com/tldr-pages/tldr/master/pages', update_cache=False)
After: Namespace(command=['svcs'], os=None, source='http://raw.github.com/tldr-pages/tldr/master/pages', update_cache=False)
```

### PR DESCRIPTION
**Pull request by MasterOdin**
Closes #62.

### CODE REVIEW

**Comment by felixonmars** [comment]
Oops, I somehow missed this one. Please resolve the conflicts and I'll merge, thanks!

**Comment by MasterOdin** [comment]
Conflicts should have already been fixed?

**Comment by felixonmars** [comment]
2018-06-04-000113-8e3947
GitHub somehow still shows as conflict.

**Comment by MasterOdin** [comment]
Hard refresh your page? I merged master and fixed the merge conflict in 439ac04 in my fork.

screenshot 2018-06-03 12 05 16

**Comment by felixonmars** [comment]
The default rebase action didn't work, but squash works :)

Thanks again!

**Pull request merged**
