### PR TITLE
update default colors to match the node client

### PR DESCRIPTION
**Pull request by waldyrious**
At the time of writing, the latest version of the node client has the following configuration:
https://github.com/tldr-pages/tldr-node-client/blob/v1.6.0/config.json

### CODE REVIEW

**Comment by waldyrious** [comment]
This should fix #7. Paging @skovhus @Konfekt @rprieto @drobati @felixonmars @igorshubovych @rakanalh @ostera @ProgVal @sbrl @glortho @kkarpieszuk

**Comment by waldyrious** [comment]
Any help addressing the Travis failure is appreciated.

**Comment by sbrl** [comment]
This looks like a good change.

After taking a look it looks like something is unhappy about the `on_black` bit in the config file.

**Comment by waldyrious** [comment]
Yeah, I noticed that the problem is in the "on_black", but any guesses at how it can be fixed?

**Comment by sbrl** [comment]
After some more digging I found a man page for the `termcolor.py` package that appears to be in use under the hood: https://pypi.python.org/pypi/termcolor

Here's what I think is an appropriate extract:

> Text highlights:
> 
>  - on_grey
>  - on_red
>  - on_green
>  - on_yellow
>  - on_blue
>  - on_magenta
>  - on_cyan
>  - on_white

Apparently `on_black` isn't supported. Theoretically speak there should be a transparent option in there somewhere, which should show in underlying terminal color (black on windows, but purple on Ubuntu)

**Comment by waldyrious** [comment]
Thanks for the info! Ok, then let's just omit the `on_black`, which is a best-effort attempt at matching the node client's current color scheme (and an improvement at that over the current configuration).

**Comment by waldyrious** [comment]
I need some help updating the test data, since it has the [current colors hardcoded](https://github.com/tldr-pages/tldr-python-client/blob/master/tests/data/gem_rendered) (ugh...)

**Comment by bwh1te** [comment]
Come on! Did you read the docs, guys? :) I had wrote about it in readme in February:
> Background color: on_blue, on_cyan, on_magenta, on_white, on_grey, on_yellow, on_red, on_green

No `on_black` as you can see.

**Comment by waldyrious** [comment]
I did read that @bwh1te, but assumed it was just an omission since that list didn't explicitly mention that it was exhaustive, and I didn't expect that termcolor implemented only a handful of colors rather than all combinations of foreground/background among the supported colors.

By the way, do you think you could lend a hand with fixing the test data?

**Comment by waldyrious** [comment]
Thanks @lots0logs for fixing the tests :)

**Comment by waldyrious** [comment]
By the way, @lots0logs, does the [failure with pypy3](https://travis-ci.org/tldr-pages/tldr-python-client/jobs/196524923) seem like something that could be easily fixed? (Just to be clear, that failure is a sub-job of the [tests for this PR](https://travis-ci.org/tldr-pages/tldr-python-client/builds/196524917), which passed since that environment is optional.)

**Comment by lots0logs** [comment]
@waldyrious Hmm..looks like the version of python3 pypy currently used for the test is too old. Let's try using the latest...

**Pull request merged**
